
image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - step:
        name: Build .NET Backend
        script:
          - dotnet --version
          - dotnet restore
          - dotnet build --configuration Release
          - dotnet test --no-build