image: mcr.microsoft.com/dotnet/sdk:8.0

definitions:
  caches:
    nuget: /root/.nuget/packages

pipelines:
  default:
    - step:
        name: Build .NET Backend
        caches:
          - nuget
        script:
          - dotnet --version
          - dotnet restore SecurityEvents.Api/SecurityEvents.Api.csproj
          - dotnet build SecurityEvents.Api/SecurityEvents.Api.csproj --configuration Release --no-restore -v minimal
          - dotnet test  SecurityEvents.Api/SecurityEvents.Api.csproj --configuration Release --no-build
